import Link from "next/link"
import { Footer } from "@/components/lens/Footer"
import { ModeNav } from "@/components/lens/ModeNav"

export const metadata = {
  title: "Terms — lenss",
  description: "The plain rules of using lenss.",
}

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-reading px-6 sm:px-8 pt-20 sm:pt-28 pb-20">
      <header className="mb-16 sm:mb-20 flex items-center justify-between">
        <Link
          href="/"
          className="font-sans text-[14px] font-medium tracking-wordmark text-ink lowercase hover:text-ink-dimmed transition-colors duration-200"
        >
          lenss
        </Link>
        <ModeNav />
      </header>

      <p className="font-sans text-[11px] font-medium uppercase tracking-label text-ink-dimmed mb-3">
        terms
      </p>
      <p className="font-serif text-[17px] leading-[1.6] text-ink mb-12">
        Plain version: lenss is a small piece of software you can use to read
        your own writing through someone else&rsquo;s eyes. By using it, you
        agree to the rules below.
      </p>

      <section className="space-y-10">
        <Block heading="Who runs lenss">
          lenss is built and operated by Ridam Khare, an independent founder
          based in India. Questions, complaints, anything that needs a human:{" "}
          <a
            href="mailto:hello@lenss.one"
            className="underline decoration-divider underline-offset-2 hover:text-ink transition-colors"
          >
            hello@lenss.one
          </a>
          .
        </Block>

        <Block heading="What lenss does">
          You paste a passage. lenss returns a reading — an interpretation of
          what your writing is doing to the person reading it. That&rsquo;s the
          whole product. It does not rewrite your draft, it does not send
          email on your behalf, it does not analyze inboxes. The reading is
          generated by a language model and is an interpretation, not a fact.
          You alone decide whether to act on it.
        </Block>

        <Block heading="Who can use it">
          You must be 18 or older, and you must use lenss for lawful
          purposes. If you paste text that contains another person&rsquo;s
          private information, you confirm you have the right to share it
          for the purpose of getting a reading.
        </Block>

        <Block heading="Accounts">
          You can use lenss without an account (limited to a few reveals per
          day). Signing up with an email or Google account unlocks more
          reveals, saved recipient profiles, and history. You are
          responsible for keeping your account secure. We use magic-link
          sign-in — clicking the link in your inbox signs you in, so treat
          that inbox the way you would treat a password.
        </Block>

        <Block heading="Free and Pro">
          lenss has two tiers. Free includes 5 reveals per day, 3 saved
          recipient profiles, and 10 checks of history. Pro is ₹1599 per
          month and includes 50 reveals per day (effectively unlimited),
          30 saved recipient profiles, longer history, and earlier access
          to new features. Pro is a monthly recurring subscription billed
          in advance by Razorpay. A 10-day free trial of Pro is available
          to new accounts; the first charge is deferred until the trial
          ends, and you can cancel before then at no cost. Refunds, billing,
          and cancellation are covered in the{" "}
          <Link
            href="/refunds"
            className="underline decoration-divider underline-offset-2 hover:text-ink transition-colors"
          >
            Refund &amp; Cancellation Policy
          </Link>
          .
        </Block>

        <Block heading="Acceptable use">
          Don&rsquo;t use lenss to harass, deceive, or manipulate other
          people. Don&rsquo;t paste content that violates someone
          else&rsquo;s rights (copyright, trade secret, confidentiality).
          Don&rsquo;t try to extract the prompts or model behavior through
          automated scraping. Don&rsquo;t use lenss to generate output you
          then attribute to a person without their consent. We reserve the
          right to refuse service and terminate accounts that do any of
          this.
        </Block>

        <Block heading="Your text, our use of it">
          Text you paste is sent to the language model that generates the
          reading. We store the text and the resulting reading in your
          account&rsquo;s history (which only you can see) and in our
          server logs for operating the service. We do not sell your text,
          do not train models on it, do not surface it publicly. See the{" "}
          <Link
            href="/privacy"
            className="underline decoration-divider underline-offset-2 hover:text-ink transition-colors"
          >
            Privacy Policy
          </Link>{" "}
          for the full picture.
        </Block>

        <Block heading="No advice, no guarantees">
          A reading is an interpretation generated by a language model. It
          can be wrong, unfair to your draft, or miss context that only you
          have. It is not legal, medical, financial, psychological, or
          professional advice. Treat it as a second opinion from a thoughtful
          friend who only knows what you typed — useful, not authoritative.
          We make no guarantee that lenss will be uninterrupted, error-free,
          or available at any given moment.
        </Block>

        <Block heading="Limitation of liability">
          To the maximum extent allowed by law, lenss is provided
          &ldquo;as is&rdquo; without warranties of any kind. We are not
          liable for indirect, incidental, or consequential damages arising
          from your use of the service. Our total liability for any claim
          related to lenss is capped at the amount you paid us in the three
          months before the claim arose (which, for free users, is zero).
        </Block>

        <Block heading="Termination">
          You can stop using lenss at any time. If you have a Pro
          subscription, cancel it from{" "}
          <Link
            href="/account"
            className="underline decoration-divider underline-offset-2 hover:text-ink transition-colors"
          >
            /account
          </Link>{" "}
          — you keep Pro access until the end of the billing period. We can
          terminate or suspend access if you violate these terms or use the
          service in a way that puts others at risk; in serious cases, we
          will do this without notice. We may also discontinue the service
          entirely with reasonable advance notice; if we do, we will refund
          any unused portion of a paid period.
        </Block>

        <Block heading="Changes to these terms">
          If we change something material in these terms — pricing, what
          we collect, how we use your text — we will update this page and
          email active Pro subscribers. The last-updated stamp at the
          bottom moves when substance moves.
        </Block>

        <Block heading="Governing law">
          These terms are governed by the laws of India. Any disputes will
          be resolved in the courts of Delhi, India.
        </Block>

        <p className="font-sans text-[12px] text-ink-dimmed pt-6">
          Last updated 2026-05-29.
        </p>
      </section>

      <Footer />
    </main>
  )
}

function Block({
  heading,
  children,
}: {
  heading: string
  children: React.ReactNode
}) {
  return (
    <div>
      <h2 className="font-sans text-[11px] font-medium uppercase tracking-label text-ink-dimmed mb-3">
        {heading}
      </h2>
      <div className="font-serif text-[16px] leading-[1.65] text-ink">
        {children}
      </div>
    </div>
  )
}
